import "./globals.css";

// Encabezado y pie de pagina
import HeaderHome from "@/components/HeaderHome";
import FooterHome from "@/components/Footer";

export const metadata = {
  title: "Brinna",
  description: "Generated by Cecilia, Daniel, Noelia",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeaderHome />
          {children}
        <FooterHome />
        </body>
    </html>
  );
}
