import "./globals.css";

export const metadata = {
  title: "Brinna",
  description: "Generated by Cecilia, Daniel, Noelia",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  );
}
